/* eslint-disable @typescript-eslint/no-var-requires */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const nextSafe = require('next-safe')

/* eslint-disable no-undef */
if (!process.env.NEXT_PUBLIC_WORDPRESS_API_URL) {
  throw new Error(`
    Please provide a valid WordPress instance URL.
    Add to your environment variables WORDPRESS_API_URL.
  `)
}

const isDev = process.env.NODE_ENV !== 'production'
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
})
/** @type {import('next').NextConfig} */
module.exports = withBundleAnalyzer({
  webpack(config) {
    // Grab the existing rule that handles SVG imports
    const fileLoaderRule = config.module.rules.find((rule) =>
      rule.test?.test?.('.svg')
    )

    config.module.rules.push(
      // Reapply the existing rule, but only for svg imports ending in ?url
      {
        ...fileLoaderRule,
        test: /\.svg$/i,
        resourceQuery: /url/, // *.svg?url
      },
      // Convert all other *.svg imports to React components
      {
        test: /\.svg$/i,
        issuer: /\.[jt]sx?$/,
        resourceQuery: { not: /url/ }, // exclude if *.svg?url
        use: ['@svgr/webpack'],
      }
    )

    // Modify the file loader rule to ignore *.svg, since we have it handled now.
    fileLoaderRule.exclude = /\.svg$/i

    return config
  },
  reactStrictMode: true,
  swcMinify: true,
  // Adding policies:
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: nextSafe({
          isDev,
          permissionsPolicy: false,
          contentSecurityPolicy: {
            reportOnly: process.env.NODE_ENV !== 'production',
            mergeDefaultDirectives: true,
            'connect-src': [
              '*.google-analytics.com',
              '*.googleapis.com',
              '*.google.com',
              '*.google-analytics.com',
              '*.googlesyndication.com',
              '*.jobrapide.org',
              '*.gstatic.com',
              'https://*.analytics.google.com',
              'https://*.googletagmanager.com',
            ],
            'font-src': 'data:',
            'frame-src': [
              '*.g.doubleclick.net',
              '*.twitter.com',
              '*.facebook.com',
              '*.googlesyndication.com',
              '*.google.com',
              '*.googleadservices.com',
              'https://*.googletagmanager.com',
            ],
            'img-src': [
              '*.jobrapide.org',
              '*.twitter.com',
              '*.facebook.com',
              '*.googleadservices.com',
              '*.googlesyndication.com',
              '*.googleapis.com',
              '*.gstatic.com',
              '*.google.com',
              '*.g.doubleclick.net',
              'https://*.google-analytics.com',
              'https://*.googletagmanager.com',
            ],
            'script-src': [
              '*.twitter.com',
              '*.facebook.net',
              '*.googleapis.com',
              '*.google.com',
              '*.google.ad',
              '*.google.ae',
              '*.google.com.af',
              '*.google.com.ag',
              '*.google.com.ai',
              '*.google.al',
              '*.google.am',
              '*.google.co.ao',
              '*.google.com.ar',
              '*.google.as',
              '*.google.at',
              '*.google.com.au',
              '*.google.az',
              '*.google.ba',
              '*.google.com.bd',
              '*.google.be',
              '*.google.bf',
              '*.google.bg',
              '*.google.com.bh',
              '*.google.bi',
              '*.google.bj',
              '*.google.com.bn',
              '*.google.com.bo',
              '*.google.com.br',
              '*.google.bs',
              '*.google.bt',
              '*.google.co.bw',
              '*.google.by',
              '*.google.com.bz',
              '*.google.ca',
              '*.google.cd',
              '*.google.cf',
              '*.google.cg',
              '*.google.ch',
              '*.google.ci',
              '*.google.co.ck',
              '*.google.cl',
              '*.google.cm',
              '*.google.cn',
              '*.google.com.co',
              '*.google.co.cr',
              '*.google.com.cu',
              '*.google.cv',
              '*.google.com.cy',
              '*.google.cz',
              '*.google.de',
              '*.google.dj',
              '*.google.dk',
              '*.google.dm',
              '*.google.com.do',
              '*.google.dz',
              '*.google.com.ec',
              '*.google.ee',
              '*.google.com.eg',
              '*.google.es',
              '*.google.com.et',
              '*.google.fi',
              '*.google.com.fj',
              '*.google.fm',
              '*.google.fr',
              '*.google.ga',
              '*.google.ge',
              '*.google.gg',
              '*.google.com.gh',
              '*.google.com.gi',
              '*.google.gl',
              '*.google.gm',
              '*.google.gr',
              '*.google.com.gt',
              '*.google.gy',
              '*.google.com.hk',
              '*.google.hn',
              '*.google.hr',
              '*.google.ht',
              '*.google.hu',
              '*.google.co.id',
              '*.google.ie',
              '*.google.co.il',
              '*.google.im',
              '*.google.co.in',
              '*.google.iq',
              '*.google.is',
              '*.google.it',
              '*.google.je',
              '*.google.com.jm',
              '*.google.jo',
              '*.google.co.jp',
              '*.google.co.ke',
              '*.google.com.kh',
              '*.google.ki',
              '*.google.kg',
              '*.google.co.kr',
              '*.google.com.kw',
              '*.google.kz',
              '*.google.la',
              '*.google.com.lb',
              '*.google.li',
              '*.google.lk',
              '*.google.co.ls',
              '*.google.lt',
              '*.google.lu',
              '*.google.lv',
              '*.google.com.ly',
              '*.google.co.ma',
              '*.google.md',
              '*.google.me',
              '*.google.mg',
              '*.google.mk',
              '*.google.ml',
              '*.google.com.mm',
              '*.google.mn',
              '*.google.ms',
              '*.google.com.mt',
              '*.google.mu',
              '*.google.mv',
              '*.google.mw',
              '*.google.com.mx',
              '*.google.com.my',
              '*.google.co.mz',
              '*.google.com.na',
              '*.google.com.ng',
              '*.google.com.ni',
              '*.google.ne',
              '*.google.nl',
              '*.google.no',
              '*.google.com.np',
              '*.google.nr',
              '*.google.nu',
              '*.google.co.nz',
              '*.google.com.om',
              '*.google.com.pa',
              '*.google.com.pe',
              '*.google.com.pg',
              '*.google.com.ph',
              '*.google.com.pk',
              '*.google.pl',
              '*.google.pn',
              '*.google.com.pr',
              '*.google.ps',
              '*.google.pt',
              '*.google.com.py',
              '*.google.com.qa',
              '*.google.ro',
              '*.google.ru',
              '*.google.rw',
              '*.google.com.sa',
              '*.google.com.sb',
              '*.google.sc',
              '*.google.se',
              '*.google.com.sg',
              '*.google.sh',
              '*.google.si',
              '*.google.sk',
              '*.google.com.sl',
              '*.google.sn',
              '*.google.so',
              '*.google.sm',
              '*.google.sr',
              '*.google.st',
              '*.google.com.sv',
              '*.google.td',
              '*.google.tg',
              '*.google.co.th',
              '*.google.com.tj',
              '*.google.tl',
              '*.google.tm',
              '*.google.tn',
              '*.google.to',
              '*.google.com.tr',
              '*.google.tt',
              '*.google.com.tw',
              '*.google.co.tz',
              '*.google.com.ua',
              '*.google.co.ug',
              '*.google.co.uk',
              '*.google.com.uy',
              '*.google.co.uz',
              '*.google.com.vc',
              '*.google.co.ve',
              '*.google.vg',
              '*.google.co.vi',
              '*.google.com.vn',
              '*.google.vu',
              '*.google.ws',
              '*.google.rs',
              '*.google.co.za',
              '*.google.co.zm',
              '*.google.co.zw',
              '*.google.cat',
              '*.gstatic.com',
              '*.googletagmanager.com',
              '*.googlesyndication.com',
              '*.googleadservices.com',
              '*.google-analytics.com',
              '*.googleapis.com',
              'vercel.live',
              "'nonce-jobrapidenoneForce'",
            ],
            'style-src': [
              '*.gstatic.com',
              '*.googleapis.com',
              '*.googlesyndication.com',
              "'unsafe-inline'",
              "'unsafe-hashes'",
            ],
            'object-src': ['data:', "'unsafe-inline'", "'unsafe-hashes'"],
          },
        }),
      },
    ]
  },
  trailingSlash: true,
  compiler: {
    removeConsole: {
      exclude: ['error'],
    },
  },
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.jobrapide.org',
      },
      {
        protocol: 'https',
        hostname: '**.gravatar.com',
      },
    ],
    formats: ['image/avif', 'image/webp'],
  },
})
